name: Build and Deploy
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -U jupyter-book
        pip install -U jsonschema[format-nongpl]
        pip freeze --all --no-input

    - name: Build
      run: |
        jupyter-book build -W -n --keep-going .

    - name: Upload
      if: |
        (
          github.event_name != 'pull_request' && github.ref_name == 'main'
        )
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        force_orphan: true
